services:
  outboxtesting.masstransit:
    image: outboxtesting.masstransit
    build:
      context: .
      dockerfile: OutboxTesting.MassTransit/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
  rabbitmq:
    image: "rabbitmq:3.13.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/data"
volumes:
  sqlserver-data:
  rabbitmq_data:
